name: Draw Keymap
on:
  workflow_dispatch: # permite rodar manualmente
  push:
    paths:
      - "config/*.keymap" # roda sempre que o keymap mudar
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Draw
        uses: caksoylar/keymap-drawer@main
        with:
          keymap_lines: 16 # ajuste para o tamanho do Sofle
          config_path: "keymap_drawer.config.yaml" # opcional
          output_path: "img/keymap.svg"
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add img/keymap.svg
          git commit -m "Update keymap SVG" || echo "No changes to commit"
          git push
